# Generated by Django 5.2.5 on 2025-08-06 17:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Savol')),
                ('option_a', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Variant A')),
                ('option_b', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Variant B')),
                ('option_c', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Variant C')),
                ('option_d', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Variant D')),
                ('correct_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name="To'g'ri javob")),
            ],
        ),
    ]
