# Generated by Django 5.2.5 on 2025-08-07 10:02

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('question_text', ckeditor.fields.RichTextField(verbose_name='📝 Savol matni (LaTeX, rasm, matn)')),
                ('option_a', ckeditor.fields.RichTextField(verbose_name='A varianti')),
                ('option_b', ckeditor.fields.RichTextField(verbose_name='B varianti')),
                ('option_c', ckeditor.fields.RichTextField(verbose_name='C varianti')),
                ('option_d', ckeditor.fields.RichTextField(verbose_name='D varianti')),
                ('correct_option', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name="To'g'ri javob")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='fortest.categories')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['-id'],
            },
        ),
    ]
