# Generated by Django 5.2.5 on 2025-08-06 18:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_answer',
            new_name='correct_option',
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=ckeditor.fields.RichTextField(verbose_name='A varianti'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=ckeditor.fields.RichTextField(verbose_name='B varianti'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=ckeditor.fields.RichTextField(verbose_name='C varianti'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=ckeditor.fields.RichTextField(verbose_name='D varianti'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=ckeditor.fields.RichTextField(verbose_name='📝 Savol matni (LaTeX, rasm, matn)'),
        ),
    ]
