# Generated by Django 5.2.5 on 2025-08-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.BigIntegerField(db_index=True, unique=True)),
                ('group_name', models.CharField(max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Telegram Group',
                'verbose_name_plural': 'Telegram Groups',
                'db_table': 'telegram_groups',
            },
        ),
    ]
