# Generated by Django 5.2.5 on 2025-08-14 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortest', '0002_telegramgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='fortest.telegramgroup')),
            ],
            options={
                'verbose_name': 'Telegram User Group',
                'verbose_name_plural': 'Telegram User Groups',
                'db_table': 'telegram_user_groups',
                'unique_together': {('user_id', 'group')},
            },
        ),
    ]
