# Generated by Django 5.2.5 on 2025-08-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortest', '0002_alter_telegramsession_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
