# Generated by Django 5.2.5 on 2025-08-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortest', '0003_delete_admin_delete_telegramuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramSession',
        ),
    ]
