# Generated by Django 5.2.5 on 2025-08-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortest', '0003_telegramusergroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramUserGroup',
        ),
    ]
