# Generated by Django 5.2.5 on 2025-08-19 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortest', '0004_delete_telegramusergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='fortest.register'),
            preserve_default=False,
        ),
    ]
