# Generated by Django 5.2.5 on 2025-08-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortest', '0005_remove_testresult_telegram_id_testresult_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='wrong_answers',
        ),
    ]
